using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CPMS.Api.Controllers;

[ApiController]
[Route("api/test-support")]
[AllowAnonymous]
public sealed class TestSupportController(
    IWebHostEnvironment environment,
    IConfiguration configuration) : ControllerBase
{
    [HttpGet("swagger-guide")]
    public ActionResult<SwaggerTestGuideResponse> GetSwaggerGuide()
    {
        if (!IsEnabled())
        {
            return NotFound();
        }

        return Ok(new SwaggerTestGuideResponse(
            "Local Swagger helper for FE/manual API testing.",
            [
                "Call POST /api/auth/login with a test account.",
                "Copy accessToken from the login response.",
                "Click Authorize in Swagger and paste the accessToken value only.",
                "Use GET endpoints first to get real ids. Do not guess semesterId, lecturerId, groupId, sessionId, or submissionId.",
                "Use the role matrix below before calling protected endpoints."
            ],
            TestAccounts(),
            RoleGroups(),
            [
                "DateOnly query/body values use yyyy-MM-dd, for example 2026-06-15.",
                "DateTime body values use ISO format, for example 2026-06-15T00:00:00Z.",
                "Review dayOfWeek uses Monday=1 through Sunday=7.",
                "Review/defense slot must be 1 through 8.",
                "Common enum values: Student, Lecturer, EvaluationPanel, TrainingDepartment, Review1, Review2, Review3, Defense1, Defense2, Draft, Published, Cancelled, BaoVe, Nguoi.",
                "Account username is generated by backend from fullName and identityCode. Example: Duong Thanh Thanh Duy + SE194673 -> DuyDTTSE194673."
            ],
            [
                "Auth flow: POST /api/auth/login -> Authorize -> call protected endpoint.",
                "Account flow: login as moderator -> GET /api/accounts -> POST /api/accounts.",
                "Lecturer availability flow: login as lecturer -> GET /api/semesters/resolve -> PUT /api/review-availability/week -> GET /api/review-availability/week.",
                "Review scheduling flow: login as moderator -> GET /api/review-scheduling/board -> POST /api/review-sessions/bulk-assign -> POST /api/review-schedules/publish.",
                "Review checklist flow: login as lecturer -> GET /api/review-sessions/my -> GET /api/review-submissions/{submissionId} -> PUT draft -> POST submit.",
                "Defense flow: login as moderator to create round/board/session -> login as board lecturer -> resolve session -> chairman starts -> members submit scores -> chairman closes."
            ]));
    }

    [HttpGet("test-accounts")]
    public ActionResult<IReadOnlyCollection<TestAccountResponse>> GetTestAccounts()
    {
        if (!IsEnabled())
        {
            return NotFound();
        }

        return Ok(TestAccounts());
    }

    private bool IsEnabled() =>
        environment.IsDevelopment() || configuration.GetValue<bool>("Swagger:ExposeTestSupport");

    private static IReadOnlyCollection<TestAccountResponse> TestAccounts() =>
    [
        new("TrainingDepartment", "test.training", "Test@123456", "Use for moderator/training workflows."),
        new("Lecturer", "test.lecturer", "Test@123456", "Use for lecturer review/defense workflows."),
        new("Lecturer", "test.lecturer.nodept", "Test@123456", "Lecturer account created without department."),
        new("EvaluationPanel", "test.panel", "Test@123456", "Use for panel/evaluator login checks."),
        new("Student", "test.student", "Test@123456", "Use for student visibility checks.")
    ];

    private static IReadOnlyCollection<RoleEndpointGroupResponse> RoleGroups() =>
    [
        new("Anonymous", ["POST /api/auth/login", "POST /api/auth/refresh", "POST /api/auth/google"]),
        new("TrainingDepartment", [
            "GET/POST/PATCH /api/accounts including role account creation",
            "GET/POST /api/semesters",
            "GET /api/review-scheduling/board",
            "POST/PATCH /api/review-sessions",
            "POST /api/review-schedules/publish",
            "GET /api/review-submissions/export.zip",
            "GET/POST /api/defense-management/*"
        ]),
        new("Lecturer", [
            "GET/PUT /api/review-availability/week",
            "GET /api/review-sessions/my",
            "GET/PUT/POST /api/review-submissions/{submissionId}",
            "GET /api/defense-management/my-board-sessions",
            "GET/POST /api/defense-sessions/* when assigned to the council"
        ]),
        new("EvaluationPanel", [
            "GET /api/review-sessions/my",
            "GET/PUT/POST /api/review-submissions/{submissionId} when assigned",
            "GET /api/defense-management/my-board-sessions",
            "GET/POST /api/defense-sessions/* when assigned to the council"
        ]),
        new("Student", [
            "GET /api/semesters",
            "GET /api/review-submissions/{submissionId} only when it belongs to the student's group and is published"
        ])
    ];
}

public sealed record SwaggerTestGuideResponse(
    string Purpose,
    IReadOnlyCollection<string> HowToUseSwagger,
    IReadOnlyCollection<TestAccountResponse> LocalTestAccounts,
    IReadOnlyCollection<RoleEndpointGroupResponse> RoleEndpointGroups,
    IReadOnlyCollection<string> CommonInputRules,
    IReadOnlyCollection<string> RecommendedFlows);

public sealed record TestAccountResponse(
    string Role,
    string Username,
    string Password,
    string Note);

public sealed record RoleEndpointGroupResponse(
    string Role,
    IReadOnlyCollection<string> Endpoints);
